---
version: "3"

services:
  controller:
    image: quay.io/omaciel/ansible_lab_controller:latest
    container_name: controller
    hostname: controller
    networks:
      - ansible-net
    volumes:
      - ansible-lab-work:/root/ansible_lab_work

  host01:
    image: quay.io/omaciel/ansible_lab_host:latest
    container_name: host01
    hostname: host01
    networks:
      - ansible-net

  host02:
    image: quay.io/omaciel/ansible_lab_host:latest
    container_name: host02
    hostname: host02
    networks:
      - ansible-net

networks:
  ansible-net:

volumes:
  ansible-lab-work:
